# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9532002e19af501ac338a3348cd28d30887677cb94cde6b66f841d17eee5c1cae7fa5f9887d23f895b01120c736b7b8be39a4179dc28832b32b20e1256067e42

test:
  secret_key_base: 7256c1e16a0b2f2f5d2837e25499b32a8e95960aea381e6c8eb4a2491b08f89ce3d84b499a705ed8fb77519a17a1f407652c41dd2e612705ad6bcf8e168d3fab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
